### ISSUE TITLE
I suspect a missing ./utils/ file --- the README.md does not work on a fresh fork and clone

### ISSUE THREAD

**Issue by herrold** [ALSchwalm/pISO#15]
[herrold@centos-7 pISO]$ git clone git@github.com:herrold/pISO.git
Cloning into 'pISO'...
remote: Counting objects: 939, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 939 (delta 7), reused 14 (delta 5), pack-reused 923
Receiving objects: 100% (939/939), 3.28 MiB | 150.00 KiB/s, done.
Resolving deltas: 100% (611/611), done.
[herrold@centos-7 pISO]$ ls
pISO
[herrold@centos-7 pISO]$ cd pISO/
[herrold@centos-7 pISO]$ man sdimage
No manual entry for sdimage
[herrold@centos-7 pISO]$ make sdimage
/bin/sh: ./utils/should-rebuild: No such file or directory
cd "/home/herrold/vcs/git/foss-upstreams/pISO/pISO/buildroot" && cp "configs/raspberrypi0_defconfig" ".config"
cp: cannot stat ‘configs/raspberrypi0_defconfig’: No such file or directory
make: *** [update-config] Error 1
[herrold@centos-7 pISO]$ pwd
/home/herrold/vcs/git/foss-upstreams/pISO/pISO
[herrold@centos-7 pISO]$

**Comment by ALSchwalm** [comment]
Because pISO uses git submodules, it must be clone recursively: `git clone --recursive https://github.com/ALSchwalm/pISO.git'

**Comment by herrold** [comment]
May I ask you to verify the presence at GH of ./utils/  as 'registered' to such a recursive git pull?  I see one additional subdidrectory on my 'forked' copy, but not that one

[herrold@centos-7 pISO]$ rm -rf pISO/
[herrold@centos-7 pISO]$ git clone --recursive git@github.com:herrold/pISO.git
Cloning into 'pISO'...
remote: Counting objects: 939, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 939 (delta 7), reused 14 (delta 5), pack-reused 923
Receiving objects: 100% (939/939), 3.28 MiB | 517.00 KiB/s, done.
Resolving deltas: 100% (611/611), done.
Submodule 'buildroot' (https://github.com/ALSchwalm/buildroot) registered for path 'buildroot'
Cloning into 'buildroot'...
remote: Counting objects: 277007, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 277007 (delta 17), reused 23 (delta 6), pack-reused 276961
Receiving objects: 100% (277007/277007), 72.20 MiB | 478.00 KiB/s, done.
Resolving deltas: 100% (185698/185698), done.
Submodule path 'buildroot': checked out '1cd1292937f7422b3c22fa98c92770fc87fc692b'
[herrold@centos-7 pISO]$ pwd
/home/herrold/vcs/git/foss-upstreams/pISO
[herrold@centos-7 pISO]$ ls
pISO
[herrold@centos-7 pISO]$ cd pISO/
[herrold@centos-7 pISO]$ less README.md 
[herrold@centos-7 pISO]$ make sdimage
/bin/sh: ./utils/should-rebuild: Permission denied
cd "/home/herrold/vcs/git/foss-upstreams/pISO/pISO/buildroot" && cp "configs/raspberrypi0_defconfig" ".config"
sudo docker run -v /home/herrold/vcs/git/foss-upstreams/pISO/pISO:/pISO -w /pISO/buildroot \
        --user 500:500 \
        --rm adamschwalm/piso:latest make
[sudo] password for herrold: 
make: *** [sdimage] Error 1

[herrold@centos-7 pISO]$ make sdimage
/bin/sh: ./utils/should-rebuild: Permission denied

**Comment by ALSchwalm** [comment]
Whoops, the 'should-rebuild' helper was not marked executable. That should be fixed now. You can update with `git pull && git submodule update --recursive --remote` or just re-clone.

**Comment by ALSchwalm** [comment]
I'm going to go ahead and close this. Please let me know if you are still having issues
