### ISSUE TITLE
Vendor ID (VID) Product ID (PID) Customization Request

### ISSUE THREAD

**Issue by jark22** [ALSchwalm/pISO#34]
It would be nice to be able to change VID/PID arbitrarily using a configuration somewhere convenient.  Then you could spoof a Sandisk USB drive for example or something like that or some other specific device that was "supported/allowed"

**Comment by ALSchwalm** [comment]
I have considered this, but I hesitate to do it due to the potential legal ramifications. If someone really wants to do this, I think it is simple enough to compile the image from source with that modification.
