### ISSUE TITLE
Trouble with Windows ISOs

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/pISO#35]
Some users are reporting issues with windows isos only shows a single text file when mounted with the pISO. I need test this out.

**Comment by jact10** [comment]
I have same issue

**Comment by jact10** [comment]
UDF file system iso image; thats the problem!  ALSchwalm please check!

**Comment by jact10** [comment]
This disc contains a "UDF" file system and requires an operating system that supports the ISO-13346 "UDF" file system specification.

**Comment by jact10** [comment]
maybe this work https://ubuntuforums.org/showthread.php?t=1751442

sudo mount -t udf /dev/dvd /mnt

**Comment by jact10** [comment]
its going to be a little complicate, because you have to detect or the person manually have to choice what type of ISO is, like does YUMI

**Comment by robiwisc** [comment]
I get the same thing on various Windows based ISOs. 

> This disc contains a "UDF" file system and requires an operating system
that supports the ISO-13346 "UDF" file system specification.

**Comment by jact10** [comment]
And when I try to boot the iso, ask me for drivers

**Comment by ALSchwalm** [comment]
@jact10 I have had issues with that when I am not booting EFI (which fails for some reason on certain machines). But if you can boot the virtual cd EFI, that will probably resolve your issue.

**Comment by ALSchwalm** [comment]
If anyone is still having trouble with this, please let me know. The issue should be resolved in any release 1.1.0 or newer.
