### ISSUE TITLE
Hiding ._ (dot underscore) '.iso' files created by macOS

### ISSUE THREAD

**Issue by yllwfsh** [ALSchwalm/pISO#41]
When storing .iso files in the ISOS folder on a drive from macOS it will create ._xxxxxx.iso files (macOS specific stuff). Would it be possible to hide those files from the menu? E.g:

renzosimac:~ renzo$ ll /Volumes/Drive1/ISOS
total 635072
drwxrwxrwx  1 renzo  staff    32K Oct  5 16:36 .
drwxrwxrwx  1 renzo  staff    32K Dec 31  1979 ..
-rwxrwxrwx  1 renzo  staff   4.0K Oct  5 16:37 ._gparted-live-0.32.0-1-amd64.iso
-rwxrwxrwx@ 1 renzo  staff   310M Aug 26 11:37 gparted-live-0.32.0-1-amd64.iso

Both of these show up in the pISO menu. Of course only the 310M version is bootable.

**Comment by ALSchwalm** [comment]
I actually implemented this a couple of days ago in 5d48cf7944ff64c649e614b86ee5010fed846232. It will be in the next release.
