### ISSUE TITLE
Broken PISO

### ISSUE THREAD

**Issue by TheRealBastiaan** [ALSchwalm/pISO#43]
My piso is delivered. But I have two broken pins on the board (power pins)

**Comment by ALSchwalm** [comment]
I'm very sorry your product arrived damaged. Could you please send some pictures of the damage to 'product@piso.support', and we will put in a claim with the distributor. I apologize for the inconvenience.

**Comment by TheRealBastiaan** [comment]
No problem can happen.
Thanks for the quick response
