### ISSUE TITLE
Change hostname from "buildroot" to something different

### ISSUE THREAD

**Issue by joedemo42** [ALSchwalm/pISO#50]
Title says it all, the pISO currently advertises itself as "buildroot" in the network. Why not change this to something more friendly like "pISO" or even have a setting for it in piso.config?

**Comment by GunnarSpawn** [comment]
do you mean for the network ssid access point you create? you can change that

**Comment by joedemo42** [comment]
I am aware of that, but no, I do not mean the SSID. I mean the hostname that's advertised by the smbd. The SMB server shows up as "buildroot".

**Comment by GunnarSpawn** [comment]
true he's adding more smb features so that could be a part of it soon. I've only mainly keyed in my smb server via ip so I haven't bothered with hostname or didn't notice what it was hehe, apologies. XD
