### ISSUE TITLE
Request: Sorting menu items according to updated name set in config

### ISSUE THREAD

**Issue by yllwfsh** [ALSchwalm/pISO#59]
This is not really an issue, just a feature request:

Would it be possible to sort the menu items according to the new name that's set in the config? That way people with a lot of drives and iso's (me included) can create some order to their list :)

**Comment by ALSchwalm** [comment]
I think this is a good idea. I will probably add it as an option in the config, just to avoid changing anyone's current layout. This will probably make it in to 1.3.0

**Comment by yllwfsh** [comment]
This works amazing in version 1.3.0b2 !!! Thanks!
