### ISSUE TITLE
Only ISO files should be shown

### ISSUE THREAD

**Issue by ArdjanB** [ALSchwalm/pISO#62]
When there are non-iso files in the ISOS folder, the pISO shows them as well on the display. However, only real ISO files would make sense to mount as CD/DVD. Non-iso files can be shown when mounting the root of the container.

**Comment by ALSchwalm** [comment]
I don't really see a need for this. In general, there is no reason to limit the contents of the isos folder to just 'isos'. Specifically, while most 'isos' are iso9660, some are UDF formatted, and I imagine there are other formats as well (whatever blueray uses, for example). If the user puts something in there, they probably intend for it to be able to be selected.
