### ISSUE TITLE
Screen Flip

### ISSUE THREAD

**Issue by Tokn59** [ALSchwalm/pISO#63]
Hello, not really an issue but it would be really useful if we had an option to flip the screen so that when inserting it left or right of the Pc the text can be flipped so it's not upside down. Would that be possible ?

Thanks and kind regards,

Tony

**Comment by ALSchwalm** [comment]
Hi Tony, this feature is actually already available. You can flip the screen by long pressing the 'down' button. Thanks for the feedback though!
