### ISSUE TITLE
Overflow when choosing volume size

### ISSUE THREAD

**Issue by TheOneValen** [ALSchwalm/pISO#74]
System:
* pISO version 1.1
* 200GB microSD
* Configuration:
- Step size 2%
- Initial size 10%

Description:
- Make new Drive
- Press the lower button until reached 0 (which would make no sense, too ;))
- Press lower button again: Impossible large percentage and size is displayed.

Have not tried to make the drive (scared) but when pressing up again it looks normal again.

Greetings!
Valen

**Comment by ALSchwalm** [comment]
Thanks for the report! This will be fixed in 1.3
